[project]
name = "slidescan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pillow>=11.3.0",
    "pyserial>=3.5",
    "stitching>=0.6.1",
    "tk>=0.1.0",
]
